name: Realtime Development Stats

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: /HiiamLongdz/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "True"
#           SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
